### ISSUE TITLE
How can I retrive the email

### ISSUE THREAD

**Issue by rrfaria** [mixercommunity/passport-mixer#1]
I've installed and followed the instructions.
I put console.log on strategy to show profile payload but email is not coming

the authentication works but no email

```js
passport.use(new MixerStrategy({
    clientID: process.env.MIXER_CLIENT_ID,
    clientSecret: process.env.MIXER_CLIENT_SECRET,
    callbackURL: "/api/auth/mixer/callback",
  },
    async (accessToken, refreshToken, profile, done) => {
      console.log(profile)
      return done(null, profile);
    }
  ));

/*
  @route  /api/auth/mixer
  @desc   Login mixer
  @access public
*/
router.get('/mixer', passport.authenticate('mixer'));


/*
  @route  /api/auth/mixer/callback
  @desc   Login mixer
  @access public
*/
router.get('/mixer/callback', passport.authenticate('mixer', { successRedirect: '/dashboard',
failureRedirect: '/noinvite' }));
```

but if I access the url of api directly on browser it show the email:
https://mixer.com/api/v1/users/current

could you tell me what I did wrong?
Is it necessary setup any scope? and which one?

**Comment by rrfaria** [comment]
I found out the solution

I should set this scope:
https://dev.mixer.com/reference/oauth/scopes

please update readme with this:

```js
/*
  @route  /api/auth/mixer
  @desc   Login mixer
  @access public
*/
router.get('/mixer', passport.authenticate('mixer', { scope: ['user:details:self'] }));
```

**Comment by rrfaria** [comment]
I don't know why but when I add this scope here:
```
channel:streamKey:self
```
the authorization page shows in red letter:
```
View your channel's stream key.
```

I got error:
```
AuthorizationError
    at Strategy.OAuth2Strategy.authenticate (/node_modules/passport-oauth2/lib/strategy.js:137:25)
    at attempt (/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/node_modules/passport/lib/middleware/authenticate.js:362:7)

```

**Comment by rrfaria** [comment]
Again I found out what is happen

mixer now need you go to transmission panel and accept terms to stream and it will be enter in revision for 24h 

after that all ready it works fine.

but when it is not seted on your mixer profile the error noticed on above comment happen.

I guess it should be handled by strategy . Am I right?
